defaults:
  - data: blob
  - model: mlp
  - operator@tau1:
      - projection
  - operator@tau2:
      - swap
      - projection
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

project: "BLOB-2ST"

tau1:
  projection:
    input_dim: 0

tau2:
  swap:
    p: 2
    d: 0
  projection:
    input_dim: 0

model:
  input_size: 2

data:
  samples: 900
  type: "type11"
  with_labels: false
  data_seed: 0


train:
  seed: 0
  lr: 0.0005
  earlystopping:
    patience: 20
    delta: 0.0
  epochs: 10
  seqs: 1 # number of mini-batches
  T: 0 #Warm start number of mini-batches used for the training only
  alpha: 0.05 # significance level
  batch_size: 900
  save: true
  save_dir: "path/to/deep-anytime-testing/logs/blob/2st/"