program: train.py
method: random
metric:
  name: val_loss
  goal: minimize
parameters:
  train.lr:
    distribution: categorical
    values: [0.0005, 0.001, 0.005, 0.01]
  train.earlystopping.patience:
    distribution: categorical
    values: [10, 20, 30, 40, 50]
  model.hidden_layer_size:
    distribution: categorical
    values: [[10, 10], [20, 20], [30, 30], [40, 40], [50, 50],[10, 10, 10], [20, 20, 20], [30, 30, 30], [40, 40, 40], [50, 50, 50]]

